call mvn install:install-file -Dfile=./lib/boof/BoofCV-android-0.23.jar -DgroupId=BoofCV -DartifactId=android -Dversion=0.23 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/boof/BoofCV-calibration-0.23.jar -DgroupId=BoofCV -DartifactId=calibration -Dversion=0.23 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/boof/BoofCV-feature-0.23.jar -DgroupId=BoofCV -DartifactId=feature -Dversion=0.23 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/boof/BoofCV-geo-0.23.jar -DgroupId=BoofCV -DartifactId=geo -Dversion=0.23 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/boof/BoofCV-io-0.23.jar -DgroupId=BoofCV -DartifactId=io -Dversion=0.23 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/boof/BoofCV-ip-0.23.jar -DgroupId=BoofCV -DartifactId=ip -Dversion=0.23 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/boof/BoofCV-jcodec-0.23.jar -DgroupId=BoofCV -DartifactId=jcodec -Dversion=0.23 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/boof/BoofCV-learning-0.23.jar -DgroupId=BoofCV -DartifactId=learning -Dversion=0.23 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/boof/BoofCV-openkinect-0.23.jar -DgroupId=BoofCV -DartifactId=openkinect -Dversion=0.23 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/boof/BoofCV-recognition-0.23.jar -DgroupId=BoofCV -DartifactId=recognition -Dversion=0.23 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/boof/BoofCV-sfm-0.23.jar -DgroupId=BoofCV -DartifactId=sfm -Dversion=0.23 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/boof/BoofCV-visualize-0.23.jar -DgroupId=BoofCV -DartifactId=visualize -Dversion=0.23 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/boof/BoofCV-WebcamCapture-0.23.jar -DgroupId=BoofCV -DartifactId=WebcamCapture -Dversion=0.23 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/boof/BoofCV-xuggler-0.23.jar -DgroupId=BoofCV -DartifactId=xuggler -Dversion=0.23 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/boof/core-core-0.29.jar -DgroupId=core -DartifactId=core -Dversion=0.29 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/boof/ddogleg-ddogleg-0.9.jar -DgroupId=ddogleg -DartifactId=ddogleg -Dversion=0.9 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/boof/dense64-dense64-0.29.jar -DgroupId=dense64 -DartifactId=dense64 -Dversion=0.29 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/boof/equation-equation-0.29.jar -DgroupId=equation -DartifactId=equation -Dversion=0.29 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/boof/georegression-georegression-0.10.jar -DgroupId=georegression -DartifactId=georegression -Dversion=0.10 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/boof/simple-simple-0.29.jar -DgroupId=simple -DartifactId=simple -Dversion=0.29 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/boof/xmlpull-xmlpull-1.1.3.1.jar -DgroupId=xmlpull -DartifactId=xmlpull -Dversion=1.1.3.1 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/boof/xpp3_min-xpp3_min-1.1.4c.jar -DgroupId=xpp3_min -DartifactId=xpp3_min -Dversion=1.1.4c -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/boof/xstream-xstream-1.4.7.jar -DgroupId=xstream -DartifactId=xstream -Dversion=1.4.7 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/botlibre/botlibre-botlibre-ai.jar -DgroupId=botlibre -DartifactId=botlibre -Dversion=ai -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/facebook/facebook4j-core-2.4.8.jar -DgroupId=facebook4j -DartifactId=core -Dversion=2.4.8 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/html/htmlcleaner2_1-htmlcleaner2_1-0.1.jar -DgroupId=htmlcleaner2_1 -DartifactId=htmlcleaner2_1 -Dversion=0.1 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/httpclient/commons-codec-1.6.jar -DgroupId=commons -DartifactId=codec -Dversion=1.6 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/httpclient/httpclient-cache-4.2.5.jar -DgroupId=httpclient -DartifactId=cache -Dversion=4.2.5 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/httpclient/httpclient-httpclient-4.2.5.1.jar -DgroupId=httpclient -DartifactId=httpclient -Dversion=4.2.5.1 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/httpclient/httpcore-httpcore-4.2.4.jar -DgroupId=httpcore -DartifactId=httpcore -Dversion=4.2.4 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/httpclient/httpmime-httpmime-4.2.5.jar -DgroupId=httpmime -DartifactId=httpmime -Dversion=4.2.5 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/irc/chatengine-chatengine-0.1.jar -DgroupId=chatengine -DartifactId=chatengine -Dversion=0.1 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/jpa/eclipselink-eclipselink-0.1.jar -DgroupId=eclipselink -DartifactId=eclipselink -Dversion=0.1 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/jpa/persistence-persistence-0.1.jar -DgroupId=persistence -DartifactId=persistence -Dversion=0.1 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/jpa/postgresql-9.4-1203.jdbc4.jar -DgroupId=postgresql -DartifactId=9.4 -Dversion=1203.jdbc4 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/json/commons-beanutils-1.8.0.jar -DgroupId=commons -DartifactId=beanutils -Dversion=1.8.0 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/json/commons-collections-3.2.1.jar -DgroupId=commons -DartifactId=collections -Dversion=3.2.1 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/json/commons-lang-2.4.jar -DgroupId=commons -DartifactId=lang -Dversion=2.4 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/json/commons-logging-1.1.1.jar -DgroupId=commons -DartifactId=logging -Dversion=1.1.1 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/json/ezmorph-ezmorph-1.0.6.jar -DgroupId=ezmorph -DartifactId=ezmorph -Dversion=1.0.6 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/json/json-lib-2.3-jdk15.jar -DgroupId=json -DartifactId=lib-2.3 -Dversion=jdk15 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/jsp/servlet-servlet-api.jar -DgroupId=servlet -DartifactId=servlet -Dversion=api -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/jsp/websocket-websocket-api.jar -DgroupId=websocket -DartifactId=websocket -Dversion=api -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/junit/junit-junit-0.1.jar -DgroupId=junit -DartifactId=junit -Dversion=0.1 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/mail/dsn-dsn-1.5.1.jar -DgroupId=dsn -DartifactId=dsn -Dversion=1.5.1 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/mail/gimap-gimap-1.5.1.jar -DgroupId=gimap -DartifactId=gimap -Dversion=1.5.1 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/mail/imap-imap-1.5.1.jar -DgroupId=imap -DartifactId=imap -Dversion=1.5.1 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/mail/javax.mail-api-1.5.1.jar -DgroupId=javax.mail -DartifactId=api -Dversion=1.5.1 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/mail/javax.mail-javax.mail-1.5.1.jar -DgroupId=javax.mail -DartifactId=javax.mail -Dversion=1.5.1 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/mail/mailapi-mailapi-1.5.1.jar -DgroupId=mailapi -DartifactId=mailapi -Dversion=1.5.1 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/mail/pop3-pop3-1.5.1.jar -DgroupId=pop3 -DartifactId=pop3 -Dversion=1.5.1 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/mail/smtp-smtp-1.5.1.jar -DgroupId=smtp -DartifactId=smtp -Dversion=1.5.1 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/marytts-lang-de-5.2.jar -DgroupId=marytts -DartifactId=lang-de -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/marytts-lang-en-5.2.jar -DgroupId=marytts -DartifactId=lang-en -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/marytts-lang-fr-5.2.jar -DgroupId=marytts -DartifactId=lang-fr -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/marytts-lang-it-5.2.jar -DgroupId=marytts -DartifactId=lang-it -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/marytts-lang-lb-5.2.jar -DgroupId=marytts -DartifactId=lang-lb -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/marytts-lang-ru-5.2.jar -DgroupId=marytts -DartifactId=lang-ru -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/marytts-lang-sv-5.2.jar -DgroupId=marytts -DartifactId=lang-sv -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/marytts-lang-te-5.2.jar -DgroupId=marytts -DartifactId=lang-te -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/marytts-lang-tr-5.2.jar -DgroupId=marytts -DartifactId=lang-tr -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/marytts-runtime-5.2-jar-with-dependencies.jar -DgroupId=marytts -DartifactId=runtime-5.2-jar-with -Dversion=dependencies -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-bits1-5.2.jar -DgroupId=voice -DartifactId=bits1 -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-bits1-hsmm-5.2.jar -DgroupId=voice -DartifactId=bits1-hsmm -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-bits3-5.2.jar -DgroupId=voice -DartifactId=bits3 -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-bits3-hsmm-5.2.jar -DgroupId=voice -DartifactId=bits3-hsmm -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-camille-5.1-SNAPSHOT.jar -DgroupId=voice -DartifactId=camille-5.1 -Dversion=SNAPSHOT -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-cmu-bdl-5.2.jar -DgroupId=voice -DartifactId=cmu-bdl -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-cmu-bdl-hsmm-5.2.jar -DgroupId=voice -DartifactId=cmu-bdl-hsmm -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-cmu-nk-hsmm-5.2.jar -DgroupId=voice -DartifactId=cmu-nk-hsmm -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-cmu-rms-5.2.jar -DgroupId=voice -DartifactId=cmu-rms -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-cmu-rms-hsmm-5.2.jar -DgroupId=voice -DartifactId=cmu-rms-hsmm -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-cmu-slt-5.2.jar -DgroupId=voice -DartifactId=cmu-slt -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-cmu-slt-hsmm-5.2.jar -DgroupId=voice -DartifactId=cmu-slt-hsmm -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-dfki-obadiah-5.2.jar -DgroupId=voice -DartifactId=dfki-obadiah -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-dfki-obadiah-hsmm-5.2.jar -DgroupId=voice -DartifactId=dfki-obadiah-hsmm -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-dfki-ot-5.2.jar -DgroupId=voice -DartifactId=dfki-ot -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-dfki-ot-hsmm-5.2.jar -DgroupId=voice -DartifactId=dfki-ot-hsmm -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-dfki-pavoque-neutral-5.2.jar -DgroupId=voice -DartifactId=dfki-pavoque-neutral -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-dfki-pavoque-neutral-hsmm-5.2.jar -DgroupId=voice -DartifactId=dfki-pavoque-neutral-hsmm -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-dfki-poppy-5.2.jar -DgroupId=voice -DartifactId=dfki-poppy -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-dfki-poppy-hsmm-5.2.jar -DgroupId=voice -DartifactId=dfki-poppy-hsmm -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-dfki-prudence-5.2.jar -DgroupId=voice -DartifactId=dfki-prudence -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-dfki-prudence-hsmm-5.2.jar -DgroupId=voice -DartifactId=dfki-prudence-hsmm -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-dfki-spike-5.2.jar -DgroupId=voice -DartifactId=dfki-spike -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-dfki-spike-hsmm-5.2.jar -DgroupId=voice -DartifactId=dfki-spike-hsmm -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-enst-camille-hsmm-5.2.jar -DgroupId=voice -DartifactId=enst-camille-hsmm -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-enst-dennys-hsmm-5.2.jar -DgroupId=voice -DartifactId=enst-dennys-hsmm -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-istc-lucia-hsmm-5.2.jar -DgroupId=voice -DartifactId=istc-lucia-hsmm -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-jessica_voice-5.1-SNAPSHOT.jar -DgroupId=voice -DartifactId=jessica_voice-5.1 -Dversion=SNAPSHOT -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-marylux-lb-5.2.jar -DgroupId=voice -DartifactId=marylux-lb -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-pierre-voice-5.1-SNAPSHOT.jar -DgroupId=voice -DartifactId=pierre-voice-5.1 -Dversion=SNAPSHOT -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-upmc-jessica-hsmm-5.2.jar -DgroupId=voice -DartifactId=upmc-jessica-hsmm -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-upmc-pierre-hsmm-5.2.jar -DgroupId=voice -DartifactId=upmc-pierre-hsmm -Dversion=5.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/marytts/voice-voxforge-ru-nsh-5.0-SNAPSHOT.jar -DgroupId=voice -DartifactId=voxforge-ru-nsh-5.0 -Dversion=SNAPSHOT -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/oswap/encoder-encoder-1.2.jar -DgroupId=encoder -DartifactId=encoder -Dversion=1.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/oswap/guava-guava-0.1.jar -DgroupId=guava -DartifactId=guava -Dversion=0.1 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/oswap/jsr305-jsr305-0.1.jar -DgroupId=jsr305 -DartifactId=jsr305 -Dversion=0.1 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/oswap/owasp-java-html-sanitizer.jar -DgroupId=owasp -DartifactId=java-html -Dversion=sanitizer -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/rest/asm-asm-3.1.jar -DgroupId=asm -DartifactId=asm -Dversion=3.1 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/rest/jackson-core-asl-1.9.2.jar -DgroupId=jackson -DartifactId=core-asl -Dversion=1.9.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/rest/jackson-jaxrs-1.9.2.jar -DgroupId=jackson -DartifactId=jaxrs -Dversion=1.9.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/rest/jackson-mapper-asl-1.9.2.jar -DgroupId=jackson -DartifactId=mapper-asl -Dversion=1.9.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/rest/jackson-xc-1.9.2.jar -DgroupId=jackson -DartifactId=xc -Dversion=1.9.2 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/rest/jersey-client-1.17.1.jar -DgroupId=jersey -DartifactId=client -Dversion=1.17.1 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/rest/jersey-core-1.17.1.jar -DgroupId=jersey -DartifactId=core -Dversion=1.17.1 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/rest/jersey-json-1.17.1.jar -DgroupId=jersey -DartifactId=json -Dversion=1.17.1 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/rest/jersey-multipart-1.17.1.jar -DgroupId=jersey -DartifactId=multipart -Dversion=1.17.1 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/rest/jersey-server-1.17.1.jar -DgroupId=jersey -DartifactId=server -Dversion=1.17.1 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/rest/jersey-servlet-1.17.1.jar -DgroupId=jersey -DartifactId=servlet -Dversion=1.17.1 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/rest/jettison-jettison-1.1.jar -DgroupId=jettison -DartifactId=jettison -Dversion=1.1 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/rest/jsr311-api-1.1.1.jar -DgroupId=jsr311 -DartifactId=api -Dversion=1.1.1 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/rest/mimepull-mimepull-1.7.jar -DgroupId=mimepull -DartifactId=mimepull -Dversion=1.7 -Dpackaging=jar -DgeneratePom=true 
call mvn install:install-file -Dfile=./lib/twitter/twitter4j-core-4.0.7.jar -DgroupId=twitter4j -DartifactId=core -Dversion=4.0.7 -Dpackaging=jar -DgeneratePom=true 
