M2="~/.m2"

function check_install() {
	local var file=$1
	local var groupId=$2
	local var artifactId=$3 
	local var version=$4 
	local var packaging=$5 
	local var generatePom=$6
	
	local var groupPath=`echo "$groupId" | sed -r "s@[.]@/@g"`
	local var fileName=`echo "$file" | rev | cut -d'/' -f 1 | rev`
	
	if [ -f $M2/repository/$groupPath/$artifactId/$version/$fileName ]; then
		# Leave black
	else
		INSTALL_CMD="mvn install:install-file -Dfile=$file -DgroupId=$groupId -DartifactId=$artifactId -Dversion=$version -Dpackaging=$packaging -DgeneratePom=$generatePom" 
		$INSTALL_CMD 2>&1 | sed -u 's/^/       /'
	fi
}

check_install './lib/boof/BoofCV-android-0.23.jar' 'BoofCV' 'android' '0.23' 'jar' 'true' 
check_install './lib/boof/BoofCV-calibration-0.23.jar' 'BoofCV' 'calibration' '0.23' 'jar' 'true' 
check_install './lib/boof/BoofCV-feature-0.23.jar' 'BoofCV' 'feature' '0.23' 'jar' 'true' 
check_install './lib/boof/BoofCV-geo-0.23.jar' 'BoofCV' 'geo' '0.23' 'jar' 'true' 
check_install './lib/boof/BoofCV-io-0.23.jar' 'BoofCV' 'io' '0.23' 'jar' 'true' 
check_install './lib/boof/BoofCV-ip-0.23.jar' 'BoofCV' 'ip' '0.23' 'jar' 'true' 
check_install './lib/boof/BoofCV-jcodec-0.23.jar' 'BoofCV' 'jcodec' '0.23' 'jar' 'true' 
check_install './lib/boof/BoofCV-learning-0.23.jar' 'BoofCV' 'learning' '0.23' 'jar' 'true' 
check_install './lib/boof/BoofCV-openkinect-0.23.jar' 'BoofCV' 'openkinect' '0.23' 'jar' 'true' 
check_install './lib/boof/BoofCV-recognition-0.23.jar' 'BoofCV' 'recognition' '0.23' 'jar' 'true' 
check_install './lib/boof/BoofCV-sfm-0.23.jar' 'BoofCV' 'sfm' '0.23' 'jar' 'true' 
check_install './lib/boof/BoofCV-visualize-0.23.jar' 'BoofCV' 'visualize' '0.23' 'jar' 'true' 
check_install './lib/boof/BoofCV-WebcamCapture-0.23.jar' 'BoofCV' 'WebcamCapture' '0.23' 'jar' 'true' 
check_install './lib/boof/BoofCV-xuggler-0.23.jar' 'BoofCV' 'xuggler' '0.23' 'jar' 'true' 
check_install './lib/boof/core-core-0.29.jar' 'core' 'core' '0.29' 'jar' 'true' 
check_install './lib/boof/ddogleg-ddogleg-0.9.jar' 'ddogleg' 'ddogleg' '0.9' 'jar' 'true' 
check_install './lib/boof/dense64-dense64-0.29.jar' 'dense64' 'dense64' '0.29' 'jar' 'true' 
check_install './lib/boof/equation-equation-0.29.jar' 'equation' 'equation' '0.29' 'jar' 'true' 
check_install './lib/boof/georegression-georegression-0.10.jar' 'georegression' 'georegression' '0.10' 'jar' 'true' 
check_install './lib/boof/simple-simple-0.29.jar' 'simple' 'simple' '0.29' 'jar' 'true' 
check_install './lib/boof/xmlpull-xmlpull-1.1.3.1.jar' 'xmlpull' 'xmlpull' '1.1.3.1' 'jar' 'true' 
check_install './lib/boof/xpp3_min-xpp3_min-1.1.4c.jar' 'xpp3_min' 'xpp3_min' '1.1.4c' 'jar' 'true' 
check_install './lib/boof/xstream-xstream-1.4.7.jar' 'xstream' 'xstream' '1.4.7' 'jar' 'true' 
check_install './lib/botlibre/botlibre-botlibre-ai.jar' 'botlibre' 'botlibre' 'ai' 'jar' 'true' 
check_install './lib/facebook/facebook4j-core-2.4.8.jar' 'facebook4j' 'core' '2.4.8' 'jar' 'true' 
check_install './lib/html/htmlcleaner2_1-htmlcleaner2_1-0.1.jar' 'htmlcleaner2_1' 'htmlcleaner2_1' '0.1' 'jar' 'true' 
check_install './lib/httpclient/commons-codec-1.6.jar' 'commons' 'codec' '1.6' 'jar' 'true' 
check_install './lib/httpclient/httpclient-cache-4.2.5.jar' 'httpclient' 'cache' '4.2.5' 'jar' 'true' 
check_install './lib/httpclient/httpclient-httpclient-4.2.5.1.jar' 'httpclient' 'httpclient' '4.2.5.1' 'jar' 'true' 
check_install './lib/httpclient/httpcore-httpcore-4.2.4.jar' 'httpcore' 'httpcore' '4.2.4' 'jar' 'true' 
check_install './lib/httpclient/httpmime-httpmime-4.2.5.jar' 'httpmime' 'httpmime' '4.2.5' 'jar' 'true' 
check_install './lib/irc/chatengine-chatengine-0.1.jar' 'chatengine' 'chatengine' '0.1' 'jar' 'true' 
check_install './lib/jpa/eclipselink-eclipselink-0.1.jar' 'eclipselink' 'eclipselink' '0.1' 'jar' 'true' 
check_install './lib/jpa/persistence-persistence-0.1.jar' 'persistence' 'persistence' '0.1' 'jar' 'true' 
check_install './lib/jpa/postgresql-9.4-1203.jdbc4.jar' 'postgresql' '9.4' '1203.jdbc4' 'jar' 'true' 
check_install './lib/json/commons-beanutils-1.8.0.jar' 'commons' 'beanutils' '1.8.0' 'jar' 'true' 
check_install './lib/json/commons-collections-3.2.1.jar' 'commons' 'collections' '3.2.1' 'jar' 'true' 
check_install './lib/json/commons-lang-2.4.jar' 'commons' 'lang' '2.4' 'jar' 'true' 
check_install './lib/json/commons-logging-1.1.1.jar' 'commons' 'logging' '1.1.1' 'jar' 'true' 
check_install './lib/json/ezmorph-ezmorph-1.0.6.jar' 'ezmorph' 'ezmorph' '1.0.6' 'jar' 'true' 
check_install './lib/json/json-lib-2.3-jdk15.jar' 'json' 'lib-2.3' 'jdk15' 'jar' 'true' 
check_install './lib/jsp/servlet-servlet-api.jar' 'servlet' 'servlet' 'api' 'jar' 'true' 
check_install './lib/jsp/websocket-websocket-api.jar' 'websocket' 'websocket' 'api' 'jar' 'true' 
check_install './lib/junit/junit-junit-0.1.jar' 'junit' 'junit' '0.1' 'jar' 'true' 
check_install './lib/mail/dsn-dsn-1.5.1.jar' 'dsn' 'dsn' '1.5.1' 'jar' 'true' 
check_install './lib/mail/gimap-gimap-1.5.1.jar' 'gimap' 'gimap' '1.5.1' 'jar' 'true' 
check_install './lib/mail/imap-imap-1.5.1.jar' 'imap' 'imap' '1.5.1' 'jar' 'true' 
check_install './lib/mail/javax.mail-api-1.5.1.jar' 'javax.mail' 'api' '1.5.1' 'jar' 'true' 
check_install './lib/mail/javax.mail-javax.mail-1.5.1.jar' 'javax.mail' 'javax.mail' '1.5.1' 'jar' 'true' 
check_install './lib/mail/mailapi-mailapi-1.5.1.jar' 'mailapi' 'mailapi' '1.5.1' 'jar' 'true' 
check_install './lib/mail/pop3-pop3-1.5.1.jar' 'pop3' 'pop3' '1.5.1' 'jar' 'true' 
check_install './lib/mail/smtp-smtp-1.5.1.jar' 'smtp' 'smtp' '1.5.1' 'jar' 'true' 
check_install './lib/marytts/marytts-lang-de-5.2.jar' 'marytts' 'lang-de' '5.2' 'jar' 'true' 
check_install './lib/marytts/marytts-lang-en-5.2.jar' 'marytts' 'lang-en' '5.2' 'jar' 'true' 
check_install './lib/marytts/marytts-lang-fr-5.2.jar' 'marytts' 'lang-fr' '5.2' 'jar' 'true' 
check_install './lib/marytts/marytts-lang-it-5.2.jar' 'marytts' 'lang-it' '5.2' 'jar' 'true' 
check_install './lib/marytts/marytts-lang-lb-5.2.jar' 'marytts' 'lang-lb' '5.2' 'jar' 'true' 
check_install './lib/marytts/marytts-lang-ru-5.2.jar' 'marytts' 'lang-ru' '5.2' 'jar' 'true' 
check_install './lib/marytts/marytts-lang-sv-5.2.jar' 'marytts' 'lang-sv' '5.2' 'jar' 'true' 
check_install './lib/marytts/marytts-lang-te-5.2.jar' 'marytts' 'lang-te' '5.2' 'jar' 'true' 
check_install './lib/marytts/marytts-lang-tr-5.2.jar' 'marytts' 'lang-tr' '5.2' 'jar' 'true' 
check_install './lib/marytts/marytts-runtime-5.2-jar-with-dependencies.jar' 'marytts' 'runtime-5.2-jar-with' 'dependencies' 'jar' 'true' 
check_install './lib/marytts/voice-bits1-5.2.jar' 'voice' 'bits1' '5.2' 'jar' 'true' 
check_install './lib/marytts/voice-bits1-hsmm-5.2.jar' 'voice' 'bits1-hsmm' '5.2' 'jar' 'true' 
check_install './lib/marytts/voice-bits3-5.2.jar' 'voice' 'bits3' '5.2' 'jar' 'true' 
check_install './lib/marytts/voice-bits3-hsmm-5.2.jar' 'voice' 'bits3-hsmm' '5.2' 'jar' 'true' 
check_install './lib/marytts/voice-camille-5.1-SNAPSHOT.jar' 'voice' 'camille-5.1' 'SNAPSHOT' 'jar' 'true' 
check_install './lib/marytts/voice-cmu-bdl-5.2.jar' 'voice' 'cmu-bdl' '5.2' 'jar' 'true' 
check_install './lib/marytts/voice-cmu-bdl-hsmm-5.2.jar' 'voice' 'cmu-bdl-hsmm' '5.2' 'jar' 'true' 
check_install './lib/marytts/voice-cmu-nk-hsmm-5.2.jar' 'voice' 'cmu-nk-hsmm' '5.2' 'jar' 'true' 
check_install './lib/marytts/voice-cmu-rms-5.2.jar' 'voice' 'cmu-rms' '5.2' 'jar' 'true' 
check_install './lib/marytts/voice-cmu-rms-hsmm-5.2.jar' 'voice' 'cmu-rms-hsmm' '5.2' 'jar' 'true' 
check_install './lib/marytts/voice-cmu-slt-5.2.jar' 'voice' 'cmu-slt' '5.2' 'jar' 'true' 
check_install './lib/marytts/voice-cmu-slt-hsmm-5.2.jar' 'voice' 'cmu-slt-hsmm' '5.2' 'jar' 'true' 
check_install './lib/marytts/voice-dfki-obadiah-5.2.jar' 'voice' 'dfki-obadiah' '5.2' 'jar' 'true' 
check_install './lib/marytts/voice-dfki-obadiah-hsmm-5.2.jar' 'voice' 'dfki-obadiah-hsmm' '5.2' 'jar' 'true' 
check_install './lib/marytts/voice-dfki-ot-5.2.jar' 'voice' 'dfki-ot' '5.2' 'jar' 'true' 
check_install './lib/marytts/voice-dfki-ot-hsmm-5.2.jar' 'voice' 'dfki-ot-hsmm' '5.2' 'jar' 'true' 
check_install './lib/marytts/voice-dfki-pavoque-neutral-5.2.jar' 'voice' 'dfki-pavoque-neutral' '5.2' 'jar' 'true' 
check_install './lib/marytts/voice-dfki-pavoque-neutral-hsmm-5.2.jar' 'voice' 'dfki-pavoque-neutral-hsmm' '5.2' 'jar' 'true' 
check_install './lib/marytts/voice-dfki-poppy-5.2.jar' 'voice' 'dfki-poppy' '5.2' 'jar' 'true' 
check_install './lib/marytts/voice-dfki-poppy-hsmm-5.2.jar' 'voice' 'dfki-poppy-hsmm' '5.2' 'jar' 'true' 
check_install './lib/marytts/voice-dfki-prudence-5.2.jar' 'voice' 'dfki-prudence' '5.2' 'jar' 'true' 
check_install './lib/marytts/voice-dfki-prudence-hsmm-5.2.jar' 'voice' 'dfki-prudence-hsmm' '5.2' 'jar' 'true' 
check_install './lib/marytts/voice-dfki-spike-5.2.jar' 'voice' 'dfki-spike' '5.2' 'jar' 'true' 
check_install './lib/marytts/voice-dfki-spike-hsmm-5.2.jar' 'voice' 'dfki-spike-hsmm' '5.2' 'jar' 'true' 
check_install './lib/marytts/voice-enst-camille-hsmm-5.2.jar' 'voice' 'enst-camille-hsmm' '5.2' 'jar' 'true' 
check_install './lib/marytts/voice-enst-dennys-hsmm-5.2.jar' 'voice' 'enst-dennys-hsmm' '5.2' 'jar' 'true' 
check_install './lib/marytts/voice-istc-lucia-hsmm-5.2.jar' 'voice' 'istc-lucia-hsmm' '5.2' 'jar' 'true' 
check_install './lib/marytts/voice-jessica_voice-5.1-SNAPSHOT.jar' 'voice' 'jessica_voice-5.1' 'SNAPSHOT' 'jar' 'true' 
check_install './lib/marytts/voice-marylux-lb-5.2.jar' 'voice' 'marylux-lb' '5.2' 'jar' 'true' 
check_install './lib/marytts/voice-pierre-voice-5.1-SNAPSHOT.jar' 'voice' 'pierre-voice-5.1' 'SNAPSHOT' 'jar' 'true' 
check_install './lib/marytts/voice-upmc-jessica-hsmm-5.2.jar' 'voice' 'upmc-jessica-hsmm' '5.2' 'jar' 'true' 
check_install './lib/marytts/voice-upmc-pierre-hsmm-5.2.jar' 'voice' 'upmc-pierre-hsmm' '5.2' 'jar' 'true' 
check_install './lib/marytts/voice-voxforge-ru-nsh-5.0-SNAPSHOT.jar' 'voice' 'voxforge-ru-nsh-5.0' 'SNAPSHOT' 'jar' 'true' 
check_install './lib/oswap/encoder-encoder-1.2.jar' 'encoder' 'encoder' '1.2' 'jar' 'true' 
check_install './lib/oswap/guava-guava-0.1.jar' 'guava' 'guava' '0.1' 'jar' 'true' 
check_install './lib/oswap/jsr305-jsr305-0.1.jar' 'jsr305' 'jsr305' '0.1' 'jar' 'true' 
check_install './lib/oswap/owasp-java-html-sanitizer.jar' 'owasp' 'java-html' 'sanitizer' 'jar' 'true' 
check_install './lib/rest/asm-asm-3.1.jar' 'asm' 'asm' '3.1' 'jar' 'true' 
check_install './lib/rest/jackson-core-asl-1.9.2.jar' 'jackson' 'core-asl' '1.9.2' 'jar' 'true' 
check_install './lib/rest/jackson-jaxrs-1.9.2.jar' 'jackson' 'jaxrs' '1.9.2' 'jar' 'true' 
check_install './lib/rest/jackson-mapper-asl-1.9.2.jar' 'jackson' 'mapper-asl' '1.9.2' 'jar' 'true' 
check_install './lib/rest/jackson-xc-1.9.2.jar' 'jackson' 'xc' '1.9.2' 'jar' 'true' 
check_install './lib/rest/jersey-client-1.17.1.jar' 'jersey' 'client' '1.17.1' 'jar' 'true' 
check_install './lib/rest/jersey-core-1.17.1.jar' 'jersey' 'core' '1.17.1' 'jar' 'true' 
check_install './lib/rest/jersey-json-1.17.1.jar' 'jersey' 'json' '1.17.1' 'jar' 'true' 
check_install './lib/rest/jersey-multipart-1.17.1.jar' 'jersey' 'multipart' '1.17.1' 'jar' 'true' 
check_install './lib/rest/jersey-server-1.17.1.jar' 'jersey' 'server' '1.17.1' 'jar' 'true' 
check_install './lib/rest/jersey-servlet-1.17.1.jar' 'jersey' 'servlet' '1.17.1' 'jar' 'true' 
check_install './lib/rest/jettison-jettison-1.1.jar' 'jettison' 'jettison' '1.1' 'jar' 'true' 
check_install './lib/rest/jsr311-api-1.1.1.jar' 'jsr311' 'api' '1.1.1' 'jar' 'true' 
check_install './lib/rest/mimepull-mimepull-1.7.jar' 'mimepull' 'mimepull' '1.7' 'jar' 'true' 
check_install './lib/twitter/twitter4j-core-4.0.7.jar' 'twitter4j' 'core' '4.0.7' 'jar' 'true' 
